In [2]:
import numpy as np

In [3]:
array1d = np.arange(start=1, stop=10)
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]

print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [4]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [5]:
print(array1d[array1d > 5])

[6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
- 행렬 정렬

In [6]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬')

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)

원본 행렬
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [7]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


위의 코드는 slicing의 3번째 인자를 응용한 코드라고 생각된다. slicing의 3번째 인자는 step 인데, -1을 주면 값을 거꾸로 가져온다. 즉, 소팅을 한 다음 그 값을 거꾸로 가져오니 내림차순 정렬이 되는 것.

In [8]:
array2d = np.array([[8, 12], [7, 1]])

# 2차원은 정렬 시, 기준 axis를 전달해야 함. 2d의 경우 0: row, 1: column
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)


로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- argsort

In [9]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [10]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array[::-1]))

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


[1 3 5 9]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


**key-value 형태의 데이터 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 nd array로 만들고, argsort()를 이용하여 key값 정렬해보기**

In [12]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스를 반환하고, 이를 이용하여 name_array에서 name 값 추출
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)

name_array_sort = name_array[sort_indices]
score_array_sort = score_array[sort_indices]

print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [14]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
