In [2]:
import numpy as np

- astype()을 통한 타입 변환

In [3]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray에서 axis 기반의 연산함수 수행 

In [5]:
array2 = np.array([[1, 2, 3],
                    [2, 3, 4]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


- ndarray를 편리하게 생성하기 - arange, zeros, ones 

In [6]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [7]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 shape를 변경하는 reshpe()

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# 변환할 수 없는 shape 구조를 입력하면 오류 발생.
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

reshape()에 -1 인자값을 전달하여 특정 차원으로 고정된 가변적인 ndarray 형태 변환

In [12]:
array1 = np.arange(10)
print(array1)

# 컬럼 axis 크기는 5에 고정하고 로우 axis 크기를 이에 맞춰 자동으로 변환, 즉 2x5 형태로 맞춰져서 변환
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
print('array2:\n', array2)

# 로우 axis 크기는 5로 고정하고, 컬럼 axis 크기를 이에 맞춰 자동으로 변환, 즉 5x2 형태로 맞춰져서 변환
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)
print('array3:\n', array3)



[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# reshape()는 (-1, 1), (-1, )와 같은 형태로 주로 사용됨.
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용.
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼 axis 크기는 반드시 1이여야 함.
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n", array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [15]:
# -1 을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생.
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
# 반드시 -1 값은 한 번만 사용해야 함.
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

### ndarray의 데이터 셋 선택하기 - 인덱싱(Indexing)

**특정 위치의 단일값 추출**


In [17]:
# 1에서부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 싲가하므로, array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [18]:
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [19]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


**슬라이싱(Slicing)**

In [22]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [23]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)
# 슬라이싱을 하면 새로운 nd array 객체가 생성되어 반환된다.
print(id(array1), id(array6))

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
139789955579696 139789955621200


In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


**팬시 인덱싱(fancy indexing)**

In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] :\n', array3, '\n')

array4 = array2d[[0, 2], 0:2]
print('array2d[[0, 2], 0:2] :\n', array4, '\n')

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] :\n', array5, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] :
 [3 6] 

array2d[[0, 2], 0:2] :
 [[1 2]
 [7 8]] 

array2d[[0, 1]] :
 [[1 2 3]
 [4 5 6]] 



**불린 인덱싱(Boolean Indexing)**

In [32]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [33]:
print(array1d > 5)

var1 = array1d > 5
print("var1:", var1)
print(type(var1))

[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [34]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용
print(array1d)
array3 = array1d[array1d > 5]



[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


뇌피셜로 추측해보면 위의 식이 평가되는 순서는 다음과 같음.
1. 

In [ ]:
# True에 해당하는 값들에 대해서 필터링됨
# 마치 filter 함수로 해서, item > 5 와 비슷한 방식
print('array1d > 5 불린 인덱싱 결과 값 :', array3)


In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)
